object CustomerInfoFrm: TCustomerInfoFrm
  Left = 0
  Top = 0
  Width = 260
  Height = 171
  ParentShowHint = False
  ShowHint = True
  TabOrder = 0
  object gbInfo: TGroupBox
    Left = 0
    Top = 0
    Width = 260
    Height = 171
    Align = alClient
    Caption = ' .:: '#1040#1073#1086#1085#1077#1085#1090' ::. '
    TabOrder = 0
    object memAbonent: TMemo
      Left = 2
      Top = 52
      Width = 256
      Height = 117
      TabStop = False
      Align = alClient
      BevelInner = bvNone
      BevelOuter = bvNone
      BorderStyle = bsNone
      Color = clBtnFace
      Ctl3D = True
      Lines.Strings = (
        #1048#1053#1060#1054)
      ParentCtl3D = False
      ReadOnly = True
      ScrollBars = ssVertical
      TabOrder = 0
    end
    object lblFIO: TDBEditEh
      Left = 2
      Top = 15
      Width = 256
      Height = 18
      Align = alTop
      BevelInner = bvNone
      BevelOuter = bvNone
      BorderStyle = bsNone
      Color = clBtnFace
      DynProps = <>
      EditButtons = <>
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      Flat = True
      ParentFont = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 1
      Text = #1060#1048#1054
      Visible = True
    end
    object lblDebt: TDBEditEh
      Left = 2
      Top = 33
      Width = 256
      Height = 19
      Align = alTop
      AutoSelect = False
      AutoSize = False
      BevelInner = bvNone
      BevelOuter = bvNone
      BorderStyle = bsNone
      Color = clBtnFace
      DynProps = <>
      EditButtons = <>
      EmptyDataInfo.Text = #1041#1040#1051#1040#1053#1057
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      TabOrder = 2
      Visible = True
    end
  end
end
