CREATE COLLATION NUMBERSORT FOR UTF8 FROM UNICODE CASE INSENSITIVE 'NUMERIC-SORT=1';

CREATE DOMAIN D_ACCOUNT_NS AS VARCHAR(15) CHARACTER SET UTF8 COLLATE NUMBERSORT;
CREATE DOMAIN D_FLAT_NS AS VARCHAR(100) CHARACTER SET UTF8 COLLATE NUMBERSORT;
CREATE DOMAIN D_VARCH10_NS AS VARCHAR(10) CHARACTER SET UTF8 COLLATE NUMBERSORT;
CREATE DOMAIN D_VARCH20_NS AS VARCHAR(20) CHARACTER SET UTF8 COLLATE NUMBERSORT;
CREATE DOMAIN D_VARCH5_NS AS VARCHAR(5) CHARACTER SET UTF8 COLLATE NUMBERSORT;

ALTER TABLE CUSTOMER DROP CONSTRAINT UNQ_CUSTOMER_ACCOUNT;
ALTER TABLE CUSTOMER ALTER COLUMN ACCOUNT_NO TYPE D_ACCOUNT_NS;
ALTER TABLE CUSTOMER ADD CONSTRAINT UNQ_CUSTOMER_ACCOUNT UNIQUE (ACCOUNT_NO) USING INDEX UNQ_CUSTOMER_ACCOUNT;

ALTER TABLE HOUSEFLATS DROP CONSTRAINT UNQ_HOUSEFLATS;
ALTER TABLE HOUSEFLATS ALTER COLUMN FLAT_NO TYPE D_FLAT_NS;
ALTER TABLE HOUSEFLATS ADD CONSTRAINT UNQ_HOUSEFLATS UNIQUE (HOUSE_ID,FLAT_NO) USING INDEX UNQ_HOUSEFLATS;

