ALTER TABLE HOUSE ADD LAT_N NUMERIC(10,6);
ALTER TABLE HOUSE ADD LON_N NUMERIC(10,6);
UPDATE HOUSE H SET LAT_N = LATITUDE, LON_N = LONGITUDE;
ALTER TABLE HOUSE DROP LATITUDE;
ALTER TABLE HOUSE DROP LONGITUDE;

ALTER TABLE GPS_LOG ADD LAT_N NUMERIC(10,6);
ALTER TABLE GPS_LOG ADD LON_N NUMERIC(10,6);
UPDATE GPS_LOG SET LAT_N = LAT, LON_N = LON;
ALTER TABLE GPS_LOG DROP LAT;
ALTER TABLE GPS_LOG DROP LON;

ALTER TABLE NODES ADD LAT_N NUMERIC(10,6);
ALTER TABLE NODES ADD LON_N NUMERIC(10,6);
UPDATE NODES SET LAT_N = LAT, LON_N = LON;
ALTER TABLE NODES DROP LAT;
ALTER TABLE NODES DROP LON;

DROP DOMAIN D_GEOPOINT;
CREATE DOMAIN D_GEOPOINT AS NUMERIC(15,12);

ALTER TABLE HOUSE ADD LATITUDE D_GEOPOINT;
ALTER TABLE HOUSE ADD LONGITUDE D_GEOPOINT;
UPDATE HOUSE SET LATITUDE = LAT_N, LONGITUDE = LON_N;
ALTER TABLE HOUSE DROP LAT_N;
ALTER TABLE HOUSE DROP LON_N;

ALTER TABLE GPS_LOG ADD LAT D_GEOPOINT;
ALTER TABLE GPS_LOG ADD LON D_GEOPOINT;
UPDATE GPS_LOG SET LAT = LAT_N, LON = LON_N;
ALTER TABLE GPS_LOG DROP LAT_N;
ALTER TABLE GPS_LOG DROP LON_N;

ALTER TABLE NODES ADD LAT D_GEOPOINT;
ALTER TABLE NODES ADD LON D_GEOPOINT;
UPDATE NODES SET LAT = LAT_N, LON = LON_N;
ALTER TABLE NODES DROP LAT_N;
ALTER TABLE NODES DROP LON_N;