
UPDATE OR INSERT INTO SERVICES (SERVICE_ID, SRV_TYPE_ID, SHIFT_MONTHS, NAME, DESCRIPTION, INET_SRV) VALUES (-1, -1, 0, NULL, 'служебная услуга, нужна для абонентской платы', 0) MATCHING (SERVICE_ID);
UPDATE OR INSERT INTO SERVICES (SERVICE_ID, SRV_TYPE_ID, SHIFT_MONTHS, NAME, DESCRIPTION, INET_SRV) VALUES (-2, -1, 0, 'Снятие блокировки', NULL, 0) MATCHING (SERVICE_ID);
UPDATE OR INSERT INTO SERVICES (SERVICE_ID, SRV_TYPE_ID, SHIFT_MONTHS, NAME, DESCRIPTION, INET_SRV) VALUES (-3, -1, 0, 'Автоблокировка', NULL, 0) MATCHING (SERVICE_ID);
commit;

UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (1, 'Материалы', 'Материалы') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (2, 'Вид платежа', 'Вид платежа для платежных систем') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (3, 'Тип заявок', 'Тип заявок') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (4, 'Атрибуты абонента', 'Атрибуты абонента') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (5, 'Атрибуты сетевого оборудования', 'Атрибуты сетевого оборудования') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (6, 'Атрибуты ТВ оборудования', 'Атрибуты ТВ оборудования') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (7, 'Группа сетевого оборудования', 'Группа сетевого оборудования') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (8, 'Тип обращения', 'Тип обращения') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (9, 'Тип ГС', 'Тип головной станции') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (10, 'Склад', 'Склад') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (11, 'Банк', 'Справочник банков') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (12, 'Группа контрагенов', 'Справочник групп контрагентов') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (13, 'Группы НДС', 'Справочник групп НДС') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (14, 'Группы анализа заявок', 'Группы анализа заявок') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (15, 'Вид услуг', 'Цифра, СПД и т.д.') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (16, 'Приходный документ', 'Приход материала') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (17, 'Расходный документ', 'Расход материала') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (18, 'Производитель оборудования', 'Производитель оборудования') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (19, 'Тип цифрового оборудования', 'Тип цифрового оборудования') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (20, 'IP Black list', 'IP Black list') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (21, 'MAC Black list', 'MAC Black list') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (22, 'Тип стороннего заказа', 'Тип стороннего заказа') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (23, 'Тип сообщения абоненту', 'Тип сообщения абоненту') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (24, 'Ошибки рассылки сообщений', 'Ошибки рассылки сообщений. Поле MES_RESULT таблицы MESSAGES') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (25, 'Атрибуты услуг', 'например скорость передачи') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (26, 'Статус сообщения', NULL) MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (27, 'Шаблон сообщений', NULL) MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (28, 'Тип документов движ. материалов', 'Тип документов движения материалов') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (29, 'Поставщики', 'Поставщики материалов и оборудования') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (30, 'Типы бонусов', 'Зажиты жестко, менять нельзя') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (31, 'Черный список абонентов', 'Черный список абонентов. Смотрим на персональный номер паспорта') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (32, 'Атрибуты IPTV групп', '') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (33, 'Документ абонента', 'Тип сохраненного документа абонента') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (34, 'Новости', 'Новости для отображения в ЛК абонента') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (35, 'Акции', 'Акции для отображения в ЛК абонента') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (36, 'Статус оборудования', NULL) MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (37, 'Атрибуты домов', 'Атрибуты для домов') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (38, 'Типы узлов', 'Типы узлов') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (39, 'Атрибуты узлов', 'Атрибуты узлов') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (40, 'Файлы узла', 'Тип сохраненного файла') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (41, 'Цифровой стандарт', 'Стандарт источника сиганла') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (42, 'Видеокодек', 'Тип видеокодека источника каналов') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (43, 'Кодировка сигнала', 'Кодировка источника сигнала') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (44, 'Декодеры каналов', 'Карточки / приемкники для приема каналов оператром') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (45, 'Тип контакта абонентов', 'phone / email / skype / telegram. Если у объекта O_Deleted = 1. занчит не отображать в карточке. в O_CHECK регулярка для проверки значения') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (46, 'Тип платежа', 'резерв. Не используеться.') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (47, 'Тематика каналов', 'Справочник тематик каналов. хранится в каналах как текст') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (48, 'Тип материала/оборудования', 'Справочник типов оборудования. используется в схемах узлов и оборудовании абонента') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (49, 'Тип суммы', 'Тип суммы в балансе абонента') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (50, 'Атрибуты для типа оборудования', NULL) MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (51, 'Владелец оборудования/материала', 'Склад абонент узел') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (52, 'Тип события', 'Тип события для EVENT_DETAIL') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (53, 'Тип проблем вещания', 'Тип сбоев вещания сервисов в сети') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (54, 'Решение проблем', 'Решение проблем вещания') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (55, 'Содержание блоба', 'к какому типу данных относится блоб') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (56, 'Тип кабеля', '') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (57, 'Тип порта', 'Тип порта коммутатора/устройства') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (58, 'Тип использования', 'Тип использования оборудования. служебный/абонентский') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (59, 'Вид коннектора', 'Вид коннектора кабеля') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (60, 'Состояние порта', '') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (61, 'Способ оплаты', 'Каким способом внесен платеж. нал. безнал.') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (62, 'Типы меток линий связи', 'нумерация жил на кабелях') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (63, 'Атрибуты сетей', 'Атрибуты сетей') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (64, 'Тип проч. начислений', 'Тип прочих начислений (OTHER_FEE)') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (65, 'Атрибуты любого оборудования', 'Атрибуты любого  оборудования') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (66, 'Тип документа абонента', 'Тип документа абонента для картотеки') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (67, 'Фильтр абонентов', 'Сохраненный фильтр абонентов') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (68, 'Фильтр заявок', 'Сохраненный фильтр заявок') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (69, 'Атрибуты групп оборудования', '') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (70, 'Акции', 'Акции на услуги') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (71, 'EPG lang codes', 'Список языков в EPG') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (72, 'Тип связей объектов', 'Связи между объектам базы') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (73, 'Тип обрудования', 'Тип обрудования в сети') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (74, 'Тип связи объектов', NULL) MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (75, 'Тип точки УЭ', 'Тип точки учета электроэнергии') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (76, 'Точка УЭ', 'Точка учета электроэнергии') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (77, 'Получатель оплаты электроэнергии', '') MATCHING (OT_ID);
UPDATE OR INSERT INTO OBJECTS_TYPE (OT_ID, OT_NAME, OT_DESCRIPTION) VALUES (78, 'Временные ряды', 'То для чего необходимо хранить временные показания, например тарифы') MATCHING (OT_ID);
commit;

-- Владелец оборудования/материала 51
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (0, 51, 'Склад', 'Жестко прошит в коде', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (1, 51, 'Абонент', 'Жестко прошит в коде', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (2, 51, 'Узел', 'Жестко прошит в коде', 0) MATCHING (O_ID, O_TYPE);
commit;
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (1, 55, 'Абонент', 'блобы абонента', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (2, 55, 'Заявка', 'блобы заявки', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (3, 55, 'Мат. документ', 'блобы материального документа', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (4, 55, 'Материал', 'блобы материала', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (0, 45, 'тел.', '', 0, 'Жестко прошит в коде', NULL, NULL, NULL, NULL, '') MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (1, 28, 'Приход материалов', NULL, 0, NULL, 'АКТ-ПРИХОД', NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (1, 41, 'ATSC', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (1, 42, 'MPEG-2', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (1, 43, 'ADEC', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (1, 45, 'моб.', '', 0, 'Жестко прошит в коде', NULL, NULL, NULL, NULL, '') MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (2, 28, 'Перемещение по складам', NULL, 0, NULL, 'АКТ-ПЕРЕМЕЩЕНИЕ', NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (2, 41, 'DVB-ASI', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (2, 42, 'MPEG-4', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (2, 43, 'Betacrypt', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (2, 45, 'email', '', 0, 'Жестко прошит в коде', NULL, NULL, NULL, NULL, '[a-zA-Zа-яА-Я0-9._%+-]+@[a-zA-Zа-яА-Я-9.-]+\.[a-zA-Zа-яА-Я0-9]{2,}') MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (3, 28, 'Списание материалов', NULL, 0, NULL, 'АКТ-СПИСАНИЯ', NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (3, 41, 'DVB-C', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (3, 42, 'H.265', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (3, 43, 'BISS', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (3, 45, 'skype', '', 0, NULL, NULL, NULL, NULL, NULL, '') MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (4, 28, 'Коррекция', NULL, 0, NULL, 'АКТ-ИНВЕНТАРИЗАЦИЯ', NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (4, 41, 'DVB-S', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (4, 42, 'HEVC', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (4, 43, 'Bulcrypt', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (4, 45, 'icq', '', 0, NULL, NULL, NULL, NULL, NULL, '') MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (5, 28, 'Инвентаризация', NULL, 0, NULL, 'АКТ-ИНВЕНТАРИЗАЦИЯ', NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (5, 41, 'DVB-S2', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (5, 43, 'Codicrypt', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (5, 45, 'Android', '', 1, 'Жестко прошит в коде. ИД Android клиента', NULL, NULL, NULL, NULL, '') MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (6, 41, 'DVB-T', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (6, 43, 'Conax', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (6, 45, 'iOS', '', 1, 'Жестко прошит в коде. ИД iOS клиента', NULL, NULL, NULL, NULL, '') MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (7, 41, 'DVB-T2', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (7, 43, 'Cryptoworks', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (7, 45, 'telegram', '', 1, 'Жестко прошит в коде. ИД Telegram клиента', NULL, NULL, NULL, NULL, '') MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (8, 41, 'ISDB-T', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (8, 43, 'Dreamcrypt', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (9, 43, 'DRECrypt', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (10, 43, 'EXSET', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (11, 43, 'Irdeto', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (12, 43, 'Mediaguard', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (13, 43, 'Nagravision', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (14, 43, 'Neotion SHL', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (15, 43, 'Omnicrypt', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (16, 43, 'PowerVu', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (17, 43, 'Roscrypt-M', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (18, 43, 'SkyPilot', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (19, 43, 'Verimatrix', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (20, 43, 'Viaccess', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (21, 43, 'Videoguard', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (22, 43, 'FTA', 'FTA', 0, NULL, NULL, NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (1, 28, 'Приход материалов', NULL, 0, NULL, 'АКТ-ПРИХОД', NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (2, 28, 'Перемещение по складам', NULL, 0, NULL, 'АКТ-ПЕРЕМЕЩЕНИЕ', NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (3, 28, 'Списание материалов', NULL, 0, NULL, 'АКТ-СПИСАНИЯ', NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (4, 28, 'Коррекция', NULL, 0, NULL, 'АКТ-ИНВЕНТАРИЗАЦИЯ', NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION, O_CHARFIELD, O_NUMERICFIELD, O_DATEFILED, O_DATEEND, O_CHECK) VALUES (5, 28, 'Инвентаризация', NULL, 0, NULL, 'АКТ-ИНВЕНТАРИЗАЦИЯ', NULL, NULL, NULL, NULL) MATCHING (O_ID, O_TYPE);
-- Тип кабеля 56 
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 1, 56, 'RG', 'Коаксиальный кабель', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (20, 56, 'UTP', 'незащищенная витая пара', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (21, 56, 'F/UTP', 'фольгированная витая пара', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (22, 56, 'STP', 'защищенная витая пара', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (23, 56, 'S/FTP', 'фольгированная экранированная витая пара', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (24, 56, 'SF/UTP', 'незащищенная экранированная витая пара', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (30, 56, 'FC', 'ВОЛС', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (40, 56, 'WI-FI', 'Беспроводная сеть', 0) MATCHING (O_ID, O_TYPE);
-- Тип порта 57
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 0, 57, 'RJ-45', '', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 1, 57, 'SFP', '', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 2, 57, 'SFP+', '', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 3, 57, 'QSFP+', '', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 4, 57, 'QSFP28', '', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 5, 57, 'COMBO', '', 0) MATCHING (O_ID, O_TYPE);
-- Тип использования 58 
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 0, 58, 'универсальный', '', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 1, 58, 'абонентский', '', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 2, 58, 'служебный', '', 0) MATCHING (O_ID, O_TYPE);
-- Вид коннектора 59 
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 0, 59, 'RJ-45', '', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 1, 59, 'BNC', '', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 2, 59, 'SC', '', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 3, 59, 'ST', '', 0) MATCHING (O_ID, O_TYPE); 
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 4, 59, 'FC', '', 0) MATCHING (O_ID, O_TYPE); 
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 5, 59, 'LC', '', 0) MATCHING (O_ID, O_TYPE); 
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 6, 59, 'MU', '', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 7, 59, 'F-3000', '', 0) MATCHING (O_ID, O_TYPE); 
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 8, 59, 'E-2000', '', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES ( 9, 59, 'FJ', '', 0) MATCHING (O_ID, O_TYPE);
-- Состояние порта 60 
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION) VALUES (0, 60, 'Нерабочий', '') MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION) VALUES (1, 60, 'Исправен', '') MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION) VALUES (2, 60, 'Отключен', '') MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION) VALUES (3, 60, 'Служебный', '') MATCHING (O_ID, O_TYPE);
-- Способ оплаты 61 
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION) VALUES (0, 61, 'CASH', '') MATCHING (O_ID, O_TYPE);      
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION) VALUES (1, 61, 'CARD', '') MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION) VALUES (2, 61, 'WEB', '') MATCHING (O_ID, O_TYPE);
-- Тип прочих начислений (64)
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION) VALUES (1, 64, 'Списание с заявки', '') MATCHING (O_ID, O_TYPE);      
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION) VALUES (2, 64, 'Возврат с заявки', '') MATCHING (O_ID, O_TYPE);
-- Тип прочих начислений (66)
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION) VALUES (1, 66, 'Паспорт', '') MATCHING (O_ID, O_TYPE);

UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (5, 55, 'Фильтр абонентов', 'json фильтра абонентов', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (6, 55, 'Фильтр заявок', 'json фильтра заявок', 0) MATCHING (O_ID, O_TYPE);

UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (1, 72, 'Зона обслуживания для модемов', 'Зона обслуживания для объектов (модемы зоны и прочее)', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (2, 72, 'Зона обслуживания для IP зоны', 'Зона обслуживания для объектов (модемы зоны и прочее)', 0) MATCHING (O_ID, O_TYPE);

UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION) VALUES (1, 73, 'Сетевое оборудование', '', 0, 'С') MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION) VALUES (2, 73, 'Кабельное оборудование', '', 0, 'К') MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED, O_DIMENSION) VALUES (3, 73, 'Прочее оборудование', '', 0, 'П') MATCHING (O_ID, O_TYPE);

UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (2, 74, 'Vlan', 'Привязка влана к адресу', 0) MATCHING (O_ID, O_TYPE);
UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (3, 74, 'Дерево групп оборудования', '', 0) MATCHING (O_ID, O_TYPE);

UPDATE OR INSERT INTO OBJECTS (O_ID, O_TYPE, O_NAME, O_DESCRIPTION, O_DELETED) VALUES (1, 78, 'Тариф электроэнергии', 'Ежемесмячный тариф на электроэнергию', 0) MATCHING (O_ID, O_TYPE);
commit;

UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (1, 'НАСТРОЙКИ', 'ПРОГРАММА', 'Настройка параметров системы') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (2, 'ПРОСМОТР СУММ', 'ПРОГРАММА', 'Просмотр сумм начислений/платежей') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (3, 'ПРОСМОТР ЖУРНАЛА', 'ПРОГРАММА', 'Просмотр и редактирование журнала') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (4, 'СМЕНА ПАРОЛЯ', 'ПРОГРАММА', 'Смена своего пароля') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (5, 'ПРОСМОТР СПРАВОЧНИКОВ', 'СПРАВОЧНИКИ', 'Просмотр всех справочников') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (6, 'ВСЕ ДОМА', 'ПРОГРАММА', 'Доступ ко всем домам в заявках и обращениях, без ограничения настройки AREA_LOCK') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (11, 'ЗАКРЫТИЕ', 'РАСЧЕТЫ', 'Начисление абонплаты') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (12, 'ОТКАТ', 'РАСЧЕТЫ', 'Откат на предыдущий месяц') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (13, 'ПЕРЕСЧЕТ', 'РАСЧЕТЫ', 'Пересчет периода') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (20, 'ПОЛНЫЙ ДОСТУП', 'ПЛАТЕЖИ', 'Добавление/удаление платежей в любом периоде') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (21, 'ДОБАВЛЕНИЕ', 'ПЛАТЕЖИ', 'Добавление платежа абоненту в текущем месяц или активация карт') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (22, 'УДАЛЕНИЕ', 'ПЛАТЕЖИ', 'Удаление платежа в текущем месяце или карт оплат') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (23, 'ГЕНЕРАЦИЯ КАРТ ОПЛАТ', 'ПЛАТЕЖИ', 'Генерация карт оплат') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (24, 'ПРОСМОТР КАРТ ОПЛАТ', 'ПЛАТЕЖИ', 'Просмотр карт оплат') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (25, 'ОБЕЩАННЫЙ', 'ПЛАТЕЖИ', 'Добавление обещанного платежа') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (26, 'ДОБАВЛЕНИЕ ТОЛЬКО ТЕКУЩИМ ДНЕМ', 'ПЛАТЕЖИ', 'Внимание, ограничение! Добавление и просмотр платежей только текущим днем!') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (27, 'ТОЛЬКО СВОИ ПЛАТЕЖИ', 'ПЛАТЕЖИ', 'Внимание, ограничение! Оператор видит только свои платежи и пл.документы со своими платежами') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (28, 'ПРАВКА ПЕНИ', 'ПЛАТЕЖИ', 'Разрешать изменять сумма платежа и пени при работе в режиме ПЕНИ') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (30, 'ПОЛНЫЙ ДОСТУП', 'АБОНЕНТЫ', 'Полный доступ к абонентам') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (31, 'ДОБАВЛЕНИЕ', 'АБОНЕНТЫ', 'Добавление абонента') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (32, 'УДАЛЕНИЕ', 'АБОНЕНТЫ', 'Удаление абонента') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (33, 'ИЗМЕНЕНИЕ', 'АБОНЕНТЫ', 'Изменение информации по абоненту') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (34, 'ДОБАВЛЕНИЕ УСЛУГИ', 'АБОНЕНТЫ', 'Добавление услуг абоненту') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (35, 'УДАЛЕНИЕ УСЛУГИ', 'АБОНЕНТЫ', 'Удаление услуг абоненту') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (36, 'ИЗМЕНЕНИЕ УСЛУГИ', 'АБОНЕНТЫ', 'Изменение услуг абоненту') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (37, 'ИЗМЕНЕНИЕ ИСТОРИИ', 'АБОНЕНТЫ', 'Изменение истории абонента (удаление, изменение услуг в любом периоде )') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (38, 'ПОЛНЫЙ ДОСТУП К СПД/ИНТЕРНЕТ', 'АБОНЕНТЫ', 'Полный доступ к закладе СПД и Интернет') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (64, 'ДОБАВЛЕНИ СПД/ИНТЕРНЕТ', 'АБОНЕНТЫ', 'Добавление записей в закладе СПД и Интернет') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (65, 'РЕДАКТИРОВАНИЕ СПД/ИНТЕРНЕТ', 'АБОНЕНТЫ', 'Редактирование записей в закладе СПД и Интернет') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (66, 'УДАЛЕНИЕ СПД/ИНТЕРНЕТ', 'АБОНЕНТЫ', 'Удаление записей в закладе СПД и Интернет') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (39, 'НАСТРОЙКА ЦИФРЫ', 'АБОНЕНТЫ', 'Изменение "цифры" абонента') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (40, 'ПОЛНЫЙ ДОСТУП', 'СПРАВОЧНИКИ', 'Полный доступ к справочникам') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (41, 'КОЭФФИЦИЕНТЫ', 'АБОНЕНТЫ', 'Доступ к изменению добавлению коэффициентов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (42, 'БОНУСЫ', 'АБОНЕНТЫ', 'Добавление или удаление бонусов в ручном режиме') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (43, 'ПРОСМОТР СПИСКА', 'АБОНЕНТЫ', 'Просмотр списка абонентов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (44, 'ФАЙЛЫ ДОБАВЛЕНИЕ', 'АБОНЕНТЫ', 'Добавление файлов абонента (сканов , документов)') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (45, 'ИЗМЕРЯТЬ ЛОЯЛЬНОСТЬ', 'АБОНЕНТЫ', 'Добавление оценки лояльности абонента') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (46, '1 ЗАПИСЬ', 'АБОНЕНТЫ', 'Внимание, ограничение! Отображать только одну запись в списке абонентов.') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (47, 'ПРОСМОТР БАЛАНСА', 'АБОНЕНТЫ', 'Просмотр суммы баланса абонента') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (48, 'СБРОС ПАРОЛЯ', 'АБОНЕНТЫ', 'Сгенерировать новый пароль и отобразить оператору') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (49, 'ФАЙЛЫ ИЗМЕНЕНИЕ/УДАЛЕНИЕ', 'АБОНЕНТЫ', 'Изменение / Удаление файлов абонента') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (50, 'ПОЛНЫЙ ДОСТУП', 'ЗАЯВКИ', 'Полный доступ') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (51, 'ДОБАВЛЕНИЕ', 'ЗАЯВКИ', 'Добавление заявок') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (52, 'РЕДАКТИРОВАНИЕ', 'ЗАЯВКИ', 'Редактирование заявки') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (53, 'ВЫДАЧА', 'ЗАЯВКИ', 'Выдача заявки в работу') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (54, 'ЗАКРЫТИЕ', 'ЗАЯВКИ', 'Закрытие заявки текущим месяцем') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (55, 'УДАЛЕНИЕ', 'ЗАЯВКИ', 'Удаление заявки') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (56, 'ИЗМЕНЕНИЕ ДАТЫ', 'ЗАЯВКИ', 'Возможность изменить дату на которую принята заявка') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (57, 'ЗАКРЫТИЕ ДЕНЬ', 'ЗАЯВКИ', 'Закрытие заявки текущим днем') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (58, 'ОТКАТ ЗАКРЫТИЯ', 'ЗАЯВКИ', 'Отменить закрытие заявки') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (60, 'ДИЗАЙНЕР', 'ОТЧЕТЫ', 'Доступ к дизайнеру') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (61, 'ПРОСМОТР', 'ОТЧЕТЫ', 'Просмотр отчетов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (62, 'СОХРАНЕНИЕ', 'ОТЧЕТЫ', 'Сохранение отчетов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (63, 'ЭКСПОРТ', 'ЭКСПОРТ', 'Экспорт отчетов и данных. Просмотр итоговой информации.') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (64, 'ОБОРУДОВАНИЕ АБОНЕНТА', 'АБОНЕНТЫ', 'Добавление/редактирование вкладки Оборудование у абонента') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (70, 'ИНТЕРНЕТ ПРОСМОТР', 'АБОНЕНТЫ', 'Просмотри информации закладки Интернет') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (71, 'ИНТЕРНЕТ ИЗМЕНЕНИЕ', 'АБОНЕНТЫ', 'Изменение, добавление, удаление информации закладки Интернет') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (80, 'ДОБАВЛЕНИЕ', 'ОБРАЩЕНИЯ', 'Добавление обращений абонентов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (82, 'УДАЛЕНИЕ', 'ОБРАЩЕНИЯ', 'Удаление обращений абонентов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (83, 'ИЗМЕНЕНИЯ', 'ОБРАЩЕНИЯ', 'Изменение обращений абонентов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (84, 'ПРОСМОТР ТОЛЬКО СВОИХ', 'ОБРАЩЕНИЯ', 'Внимание, ограничение! Просмотр в списке Обращений только те, которые создал пользователь.') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (90, 'ЦИФР. ОБОРУДОВАНИЕ', 'СПРАВОЧНИКИ', 'Создание редактирование цифрового оборудования') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (91, 'ИЗМЕНЕНИЕ ДЕКОДЕРОВ', 'ЦИФРА', 'Изменение декодеров') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (92, 'УДАЛЕНИЕ ДЕКОДЕРОВ', 'ЦИФРА', 'Удаление декодеров') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (100, 'РЕДКТИРОВАНИЕ', 'МОДУЛИ', 'Редактирование  и создание дополнительных модулей') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (101, 'ВЫПОЛНЕНИЕ ', 'МОДУЛИ', 'Выполнение дополнительных модулей') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (110, 'НАСТРОЙКА СХЕМЫ DVB', 'ЦИФРА', 'НАСТРОЙКА СХЕМЫ DVB') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (111, 'ПРОСМОТР СХЕМЫ DVB', 'ЦИФРА', 'ПРОСМОТР СХЕМЫ DVB') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (114, 'РЕДАКТ-Е ПРОГРАММЫ', 'EPG', 'Редактирование телепрограммы и объявлений EPG') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (115, 'НАСТРОЙКА IPTV', 'IPTV', 'НАСТРОЙКА IPTV') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (116, 'ПРОСМОТР IPTV', 'IPTV', 'ПРОСМОТР IPTV') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (120, 'ПОЛНЫЙ ДОСТУП', 'СТОРОННИЕ ЗАКАЗЫ', 'Полный доступ к сторонним заказам') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (121, 'ДОБАВЛЕНИЕ', 'СТОРОННИЕ ЗАКАЗЫ', 'Добавление сторонних заказов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (122, 'РЕДАКТИРОВАНИЕ', 'СТОРОННИЕ ЗАКАЗЫ', 'Редактирование стороннего заказа') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (123, 'УДАЛЕНИЕ', 'СТОРОННИЕ ЗАКАЗЫ', 'Удаление стороннего заказа') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (124, 'ОТОБРАЖАТЬ ТЕКУЩИЙ ДЕНЬ', 'СТОРОННИЕ ЗАКАЗЫ', 'Отображать сторонних заказов только за текущий день') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (125, 'ПРОСМОТР', 'СТОРОННИЕ ЗАКАЗЫ', 'ТОлько просмотр сторонних заказов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (141, 'РАЙОНЫ', 'СПРАВОЧНИКИ', 'Изменение справочника районов города') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (142, 'КОНТРАГЕНТЫ', 'СПРАВОЧНИКИ', 'Изменение справочника обслуживающих предприятий') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (143, 'УЛИЦЫ И ДОМА', 'СПРАВОЧНИКИ', 'Изменение справочника улиц и домов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (144, 'УЧАСТКИ И ЗВЕНЬЯ', 'СПРАВОЧНИКИ', 'Изменение справочника участков и звеньев') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (146, 'АТР.ДОМОВ', 'СПРАВОЧНИКИ', 'Изменение справочника атрибутов Домов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (147, 'ТИП ОБРАЩЕНИЙ ', 'СПРАВОЧНИКИ', 'Изменение справочника типов обращений ') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (148, 'ТИП ЗАЯВОК', 'СПРАВОЧНИКИ', 'Изменение справочника типов заявок') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (149, 'ШАБЛОНЫ ЗАЯВОК', 'СПРАВОЧНИКИ', 'Изменение справочника шаблонов заявок') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (150, 'РАБОТЫ ПО ЗАЯВКАМ', 'СПРАВОЧНИКИ', 'Изменение справочника работ по заявкам') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (151, 'МАТЕРИАЛЫ', 'СПРАВОЧНИКИ', 'Изменение справочника материалов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (152, 'ТВ КАНАЛЫ', 'СПРАВОЧНИКИ', 'Изменение справочника ТВ каналов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (153, 'ГС И ОУ', 'СПРАВОЧНИКИ', 'Изменение справочника ГС и ОУ') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (154, 'РАБОТНИКИ', 'СПРАВОЧНИКИ', 'Изменение справочника работников') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (155, 'ИСТОЧНИКИ ПЛАТЕЖЕЙ', 'СПРАВОЧНИКИ', 'Изменение справочника источников платежей') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (156, 'УСЛУГИ', 'СПРАВОЧНИКИ', 'Изменение справочника услуг') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (157, 'IP СЕТИ', 'СПРАВОЧНИКИ', 'Изменение справочника IP сетей') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (158, 'АТР.АБОНЕНТОВ', 'СПРАВОЧНИКИ', 'Изменение справочника атрибутов абонентов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (159, 'АТР.ОБОРУДОВАНИЯ', 'СПРАВОЧНИКИ', 'Изменение справочника атрибутов оборудования') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (160, 'РЕКВИЗИТЫ', 'СПРАВОЧНИКИ', 'Реквизиты предприятия') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (161, 'ГР.ОБОРУДОВАНИЯ', 'СПРАВОЧНИКИ', 'Изменение справочника групп оборудования (типов и команд)') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (162, 'ОБОРУДОВАНИЕ', 'СПРАВОЧНИКИ', 'Изменение справочника оборудования') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (163, 'ПЕЧАТНЫЕ ФОРМЫ', 'СПРАВОЧНИКИ', 'Изменение шаблонов печатных форм') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (164, 'СКЛАД', 'СПРАВОЧНИКИ', 'Изменение справочника складов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (165, 'ПОЛНЫЙ ДОСТУП', 'МАТЕРИАЛЫ', 'Полный доступ к материалам и мат. документам') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (166, 'ПРОИЗВОДИТЕЛИ', 'СПРАВОЧНИКИ', NULL) MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (167, 'БАНКИ', 'СПРАВОЧНИКИ', NULL) MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (168, 'ТИПЫ СТОР-Х ЗАКАЗОВ', 'СПРАВОЧНИКИ', 'Типы сторонних заказов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (169, 'ПОСТАВЩИКИ', 'СПРАВОЧНИКИ', 'Поставщики материалов и оборудования') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (170, 'РЕДАКТИРОВАНИЕ МАТ. ДОКУМЕНТОВ', 'МАТЕРИАЛЫ', 'Создание и редактирование документов движения материалов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (171, 'БОНУСЫ', 'СПРАВОЧНИКИ', 'Установка размера бонуса и дат действия бонусов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (172, 'РАССЫЛКА СООБЩЕНИЙ', 'ПРОГРАММА', 'Рассылка сообщений абоненту') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (173, '"ЧЕРНЫЙ" СПИСОК', 'СПРАВОЧНИКИ', 'Редактирование "черного" списка') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (174, 'АТР.УСЛУГ', 'СПРАВОЧНИКИ', 'Изменение справочника атрибутов услуг') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (175, 'АТР.IPTV', 'СПРАВОЧНИКИ', 'Изменение справочника атрибутов IPTV') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (176, 'ПРОСМОТР ЦЕН', 'МАТЕРИАЛЫ', 'Просмотр цены материала') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (178, 'СПРАВОЧНИК УЗЛОВ', 'ОБЪЕКТЫ', 'Полный доступ к узлам') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (179, 'CALLCENTER', 'ПРОГРАММА', 'Для работы службы обзвона. Список всех квартир дома') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (180, 'ПРИХОД', 'МАТЕРИАЛЫ', 'Доступ к документам прихода на склад') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (181, 'ПЕРЕМЕЩЕНИЕ', 'МАТЕРИАЛЫ', 'Доступ к документам перемещения между складами') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (182, 'СПИСАНИЕ', 'МАТЕРИАЛЫ', 'Доступ к документам списания со склада') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (183, 'ИНВЕНТАРИЗАЦИЯ', 'МАТЕРИАЛЫ', 'Доступ к документам инвентаризации') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (184, 'ДИСТРИБЬЮТОР КАНАЛОВ', 'СПРАВОЧНИКИ', 'Дистрибьюция каналов. Договора и отчеты.') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (185, 'ЗАДАЧИ ВСЕХ', 'ПРОГРАММА', 'Просмотр задач всех сотрудников') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (186, 'ЗАКРЫТИЕ МАТ. ДОКУМЕНТОВ', 'МАТЕРИАЛЫ', 'Закрытие материальных документов на которые есть права создания') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (187, 'ЗАКРЫВАТЬ СВОЮ ЗАДАЧУ', 'ПРОГРАММА', 'Закрывать задачу в которой пользователь стоит в исполнителях') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (189, 'ДОБАВЛЯТЬ, ИЗМЕНЯТЬ, УДАЛЯТЬ АТРИБУТЫ', 'АБОНЕНТЫ', 'Добавлять, изменять, удалять атрибуты абонентов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (190, 'ПРОБЛЕМЫ ВЕЩАНИЯ. ДОБАВЛЯТЬ', 'ТВ', NULL) MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (191, 'ПРОБЛЕМЫ ВЕЩАНИЯ. УДАЛЯТЬ', 'ТВ', NULL) MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (192, 'ПРОБЛЕМЫ ВЕЩАНИЯ. ЗАКРЫВАТЬ', 'ТВ', NULL) MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (193, 'ПРОБЛЕМЫ ВЕЩАНИЯ. СПРАВОЧНИКИ', 'ТВ', 'Типы проблем. Решения проблем') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (200, 'ПОЛНЫЙ ДОСТУП', 'МОБИЛЬНОЕ ПРИЛОЖЕНИЕ', 'Полный доступ к настройкам моб. приложений') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (201, 'НОВОСТИ', 'МОБИЛЬНОЕ ПРИЛОЖЕНИЕ', 'Публиковать новости') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (210, 'ПОРТЫ', 'ОБОРУДОВАНИЕ', 'Создание/редактирование портов оборудования') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (211, 'ЛИНИИ СВЯЗИ', 'ОБЪЕКТЫ', 'Создание/редактирование линий связи узлов ') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (212, 'РЕЕСТР ДОКУМЕНТОВ', 'СПРАВОЧНИКИ', 'Справочник документов абонентов (паспорта/свдиетельства и т.д.)') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (220, 'СКРЫТЬ ПЕРСОНАЛЬНЫЕ ДАННЫЕ', 'АБОНЕНТЫ', 'Внимание, ограничение! Запретить доступ к персональным данным') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (221, 'ПРОСМОТР ТВ', 'ТВ', 'Просмотр всех пунктов меню ТВ') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (222, 'ПРОСМОТР ОБЪЕКТЫ', 'ОБЪЕКТЫ', 'Просмотр всех пунктов меню ОБЪЕКТЫ') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (223, 'РЕДАКТИРОВАНИЕ КОНТАКТОВ', 'АБОНЕНТЫ', 'Возможность редактировать контакты абонента') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (224, 'ПИСЬМА', 'АБОНЕНТЫ', 'Удаление писем абонентов') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (225, 'РЕДАКТИРОВАНИЕ ЦИФРЫ', 'АБОНЕНТЫ', 'Редактировани закладки цифры у абонента') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (226, 'ПРОСМОТР ТОЛЬКО ТЕКУЩЕГО ДНЯ', 'ОБРАЩЕНИЯ', 'Внимание, ограничение! Добавление и просмотр обращений только текущим днем!') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (227, 'ПРОСМОТР ВСЕХ МАТ. ДОКУМЕНТОВ', 'МАТЕРИАЛЫ', 'Просмотр всех типов материальных документов без учета прав создани') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (59,  'ВЫКУП', 'ЗАЯВКИ', 'Выкуп оборудования у абонента') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (228, 'ВОЗВРАТ ВСЕГО', 'ЗАЯВКИ', 'Возврат любого материала, а не только того что был у абонента/узла') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (229, 'Учет электроэнергии ', 'ЭЛЕКТРОЭНЕРГИЯ', 'Работа с показателями электроэнергии') MATCHING (ID);
UPDATE OR INSERT INTO SYS$RIGHTS (ID, RIGHTS, CATEGORY, NOTICE) VALUES (230, 'Хронологические данные', 'СПРАВОЧНИКИ', 'Внесение переодических данных') MATCHING (ID);
commit;

execute block as
declare variable v varchar(1000);
declare variable s varchar(50);
begin
  s = 'ROW_HL_COLOR';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (upper(:s), '', 'STRING', NULL, 'Цвет выделения строки') 
    MATCHING (VAR_NAME);
  s = 'ROW_HL_ID';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (upper(:s), '', 'INTEGER', NULL, 'ID объекта выделения')  
    MATCHING (VAR_NAME);
  s = 'ROW_HL_TYPE';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (upper(:s), '', 'INTEGER', NULL, 'Тип подсветки. 0-есть разовая услуга') 
    MATCHING (VAR_NAME);
  s = 'SQL_CONNECTED';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (upper(:s), 'iif(exists(select ss.Customer_Id from SUBSCR_SERV ss where ss.CUSTOMER_ID = c.CUSTOMER_ID and ss.STATE_SGN = 1) ,1, 0)', 'STRING', NULL, 'Возможность настроить запрос определения подключени ли абонент') 
    MATCHING (VAR_NAME);  
  s = 'STRICT_MODE';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (upper(:s), '0', 'BOOLEAN', 'Строгий режим', 'Запрет изменений начислений и платежей в прошлых периодах')  
    MATCHING (VAR_NAME);  
  s = 'AREA_LOCK';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (upper(:s), '', 'STRING', NULL,  'список ид (1,2) райнов для которых можно принимать заявки и обращения')
    MATCHING (VAR_NAME);
  s = 'SHOW_DOC_LIST';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (upper(:s), '0', 'BOOLEAN', NULL,  'Отображать реестр документов абонентов')
    MATCHING (VAR_NAME);
  v = null;
  select VAR_VALUE from SETTINGS where upper(VAR_NAME) = 'REQ_CLOSE_CLEAN_LAN'
  into :v;
  if (v is null) then begin
    update or insert into SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE)
    values ('REQ_CLOSE_CLEAN_LAN', '', 'STRING', NULL, 'Список типов Rqtl_Id заявок после закрытия которых удалять настройки спд абонента')
    matching (VAR_NAME);
  end
  v = null;
  select VAR_VALUE from SETTINGS where upper(VAR_NAME) = 'REQ_CLOSE_CLEAN_DVB'
  into :v;
  if (v is null) then begin
    update or insert into SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE)
    values ('REQ_CLOSE_CLEAN_DVB', '', 'STRING', NULL, 'Список типов Rqtl_Id заявок после закрытия которых удалять настройки DVB абонента')
    matching (VAR_NAME);
  end
  v = null;
  select VAR_VALUE from SETTINGS where upper(VAR_NAME) = 'PREPAY_CLEAR'
  into :v;
  if (v is null) then begin
    update or insert into SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE)
    values ('PREPAY_CLEAR', '1', 'BOOLEAN', NULL, 'Удалять обещанный при внесение любой суммы, иначе уменьшим на сумму платежа')
    matching (VAR_NAME);
  end
  v = null;
  select VAR_VALUE from SETTINGS where upper(VAR_NAME) = 'DAILY_FEE'
  into :v;
  if (v is null) then begin
    update or insert into SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE)
    values ('DAILY_FEE', '0', 'BOOLEAN', NULL, 'Записывать начисления в ежедневную таблицу')
    matching (VAR_NAME);
  end
  v = null;
  select VAR_VALUE from SETTINGS where upper(VAR_NAME) = 'FLAT_OWNER'
  into :v;
  if (v is null) then begin
    update or insert into SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE)
    values ('FLAT_OWNER', '0', 'BOOLEAN', NULL, 'Информация о владельце квартиры (Собственник/аренда)')
    matching (VAR_NAME);
  end
  v = null;
  select VAR_VALUE from SETTINGS where upper(VAR_NAME) = 'LAN_DOCSYS'
  into :v;
  if (v is null) then begin
    update or insert into SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE)
    values ('LAN_DOCSYS', '0', 'BOOLEAN', NULL, 'Сеть построена на DocSYS')
    matching (VAR_NAME);
  end
  v = null;
  select VAR_VALUE from SETTINGS where upper(VAR_NAME) = 'LAN_ADDRES'
  into :v;
  if (v is null) then begin
    update or insert into SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE)
    values ('LAN_ADDRES', '0', 'BOOLEAN', NULL, 'Адрес подключения сети у абонента может отличаться от фактического')
    matching (VAR_NAME);
  end
  s = 'LAN_VALANDISABLE';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (upper(:s), '0', 'BOOLEAN', NULL, 'Отключить влан для сети абонента')
    MATCHING (VAR_NAME);
  s = 'LAN_PORTDICTDISABLE';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (upper(:s), '0', 'BOOLEAN', NULL, 'Отключить выбор порта из списка для сети абонента')
    MATCHING (VAR_NAME);
  s = 'INFO_PANEL';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (upper(:s), '', 'STRING', NULL, 'HTML для инфо панели абонента. Если не влазит текст, то можно разить по настройкм INFO_PANEL + INFO_PANEL_1 + INFO_PANEL_2. Для группы пользователей можно задать переменные INFO_PANEL INFO_PANEL_1 INFO_PANEL_2')
    MATCHING (VAR_NAME);
  s = 'INFO_PANEL_GR';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (upper(:s), '', 'STRING', NULL, 'HTML для инфо панели абонента. Если не влазит текст, то можно разить по настройкм INFO_PANEL + INFO_PANEL_1 + INFO_PANEL_2. Для группы пользователей можно задать переменные INFO_PANEL_GRXXX INFO_PANEL_GRXXX_1 INFO_PANEL_GRXXX_2')
    MATCHING (VAR_NAME);
  s = 'INFO_PANEL_SQL';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (upper(:s), '', 'STRING', NULL, 'SQL для инфо панели абонента. Если не влазит текст, то можно разить по настройкм INFO_PANEL_SQL + INFO_PANEL_SQL_1 + INFO_PANEL_SQL_2. Для группы пользователей можно задать переменные INFO_PANEL_SQL_GRXXX INFO_PANEL_SQL_GRXXX_1 INFO_PANEL_SQL_GRXXX_2')
    MATCHING (VAR_NAME);
  s = 'LAN_TAG_LIST';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (upper(:s), '', 'STRING', NULL, 'Список значений для строково тага в параметрах СПД абонента. разделитель запятая')
    MATCHING (VAR_NAME);
  s = 'REQ_IGNORE_CLOSED';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (upper(:s), '', 'BOOLEAN', NULL, 'Отключить запрет редактирования работ и материалов в закрытых заявках')
    MATCHING (VAR_NAME);
  s = 'LAN_SRV_EXISTS';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '', 'BOOLEAN', NULL, 'Добавлять порт только если есть услуга СПД') 
    MATCHING (VAR_NAME);
  s = 'PAY_SRV_FILTER';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '', 'STRING', NULL, 'sql для фильтрации услуг в окне приема платежа') 
    MATCHING (VAR_NAME);
  s = 'IP_UNIQ_GLOBAL';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '0', 'BOOLEAN', NULL, 'IP уникален для всех, а не только для влана') 
    MATCHING (VAR_NAME);
  s = 'ZERO4LIST';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '0', 'FLOAT', NULL, 'что считать 0 для отключенных абонентов ') 
    MATCHING (VAR_NAME);
  s = 'REQ_WORKS_NOT_CALC';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '0', 'BOOLEAN', NULL, 'Отображать НЕ НАЧИСЛЯТЬ в работах заявки') 
    MATCHING (VAR_NAME);
  s = 'PAY_INPUT_SHOW';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '0', 'BOOLEAN', NULL, 'Отображение поля выбора способа оплаты при вводе платежа') 
    MATCHING (VAR_NAME);
  s = 'RQ_PHONE_ONLY_NOTYFY';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '0', 'BOOLEAN', NULL, 'При поиске абонентов выводить только телефоны с уведомлением') 
    MATCHING (VAR_NAME);
  s = 'EMAIL_CHECK';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '0', 'BOOLEAN', NULL, 'Отсылаем чеки на почту, а не смс') 
    MATCHING (VAR_NAME);
  s = 'REQUEST_TYPE_RESTRICT';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '0', 'BOOLEAN', NULL, 'Ограничить типы заявок группе пользователей') 
    MATCHING (VAR_NAME);
  s = 'RECALC_CURRENT_WHEN_CLOSE_MONTH';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '0', 'BOOLEAN', NULL, 'Пересчитываем текущий месяц, когда переходим на следующий') 
    MATCHING (VAR_NAME);
  s = 'SRV_PREPAY_IGNORE';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '', 'STRING', NULL, 'Список ИД услуг (разедлитель , 1,2,3) для которых GET_RECOMMENDED_PREPAY выдает 0') 
    MATCHING (VAR_NAME);
  s = 'PORT_LINE_LIMIT';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '0', 'BOOLEAN', NULL, 'Предлагать абоненту подключать только порт с линией связи') 
    MATCHING (VAR_NAME);
  s = 'SHOW_LCPS';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '0', 'BOOLEAN', NULL, 'Отображать платежи в локальной валюте, при мультивалютном режиме') 
    MATCHING (VAR_NAME);
  s = 'FT_CHECK_PERMISSIONS';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '', 'STRING', NULL, 'Имя процедура проверки разрешения добавления файла абоненту Prohibit (1-запрет, 0-предупреждение) (select Prohibit, Prohibit_text from FT_CHECK_PERMISSIONS(CUSTOMER_ID, FileType_ID))')
    MATCHING (VAR_NAME);

  s = 'FT_CHECK_SAVE';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '', 'STRING', NULL, 'Имя процедура проверки разрешения сохранения файла абонент Prohibit (1-запрет, 0-предупреждение) (select Prohibit, Prohibit_text from FT_CHECK_SAVE(CUSTOMER_ID, FileType_ID))')
    MATCHING (VAR_NAME);

  s = 'CALC3_DAYLY_FOR_NEW_ONLY';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_NOTICE)
    VALUES (:s, '0', 'INTEGER', 'Алгоритм 3 расчета абонплаты (1-ый месяц пропорционально дням, далее фикса)
       если 1, то считаем первый месяц по дням только для новых абонентов, если не было услуг ранее
       если 0, то считаем если не было услуги, которую просчитываем ранее.')
    MATCHING (VAR_NAME);
  s = 'ACC_KEEP_SEQ';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_NOTICE)
    VALUES (:s, '0', 'BOOLEAN', 'Сохраняем последовательность номера ЛС при отмене создания новго абонента')
    MATCHING (VAR_NAME);
  s = 'FP_ADDRESS_CHECK';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_NOTICE)
    VALUES (:s, '0', 'BOOLEAN', 'Проверять права на справочник улиц при сохранении подъезда/этажа')
    MATCHING (VAR_NAME);

  s = 'BLOCK_SRV_AFTER_DEL_PREPAY';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '0', 'BOOLEAN', NULL, 'Блокируем услуги после снятия обещанного')
    MATCHING (VAR_NAME);

  s = 'REQUEST_WORKS_DEL_RESTRICT';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '0', 'BOOLEAN', NULL, 'Разрешение удалять работы в заявке добавленные автоматически')
    MATCHING (VAR_NAME);

  s = 'PAY_AFTER_SAVE';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '', 'STRING', NULL, 'Процедура вида XXX(PAYMENT_ID) которая выполняется после сохранения платежа')
    MATCHING (VAR_NAME);

  s = 'DAILY_SINGLE_FEE';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '0', 'BOOLEAN', NULL, 'Начислять ли разовые при закрытии дня или, как прежде, начислять при закрытии месяца и добавлении услуги')
    MATCHING (VAR_NAME);

  s = 'EQUIPMENT_NODE_REQUIRED';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '0', 'BOOLEAN', NULL, 'Требовать укзание узла при редактировании оборудования')
    MATCHING (VAR_NAME);

  s = 'FILES_GRID_COLOR_SQL';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '', 'STRING', NULL, 'Запрос управления цветом для строки таблицы файлов')
    MATCHING (VAR_NAME);

  s = 'NODE_LAYOUT';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '0', 'BOOLEAN', NULL, 'Включить компановку узла и контроль материалов по нему на заявках')
    MATCHING (VAR_NAME);

  s = 'BIDS_SHOW_TABFILTER';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '0', 'BOOLEAN', NULL, 'В фильтре заявок отображать условие "Страница" для настройки разного фильтра для разной страницы')
    MATCHING (VAR_NAME);

  s = 'A4ON_EPG_PROXY';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '', 'STRING', NULL, 'урл прокси для загрузки епг http://api.a4on.net/epg/')
    MATCHING (VAR_NAME);
	
  s = 'REQUEST_ALLOW_EMPTY_PHONE';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '0', 'BOOLEAN', NULL, 'Разрешить создавать заявку без указания телефона')
    MATCHING (VAR_NAME);

  s = 'REQUEST_SINGLE_GIVE';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '0', 'BOOLEAN', NULL, 'В заявке форма выдачи для ОДНОГО матирала')
    MATCHING (VAR_NAME);

  s = 'SAVE_DAILY_MAT_REMAIN';
  if (not exists(select VAR_NAME from SETTINGS where upper(VAR_NAME) = upper(:s))) then
    UPDATE OR INSERT INTO SETTINGS (VAR_NAME, VAR_VALUE, VAR_TYPE, VAR_CAPTION, VAR_NOTICE) 
    VALUES (:s, '0', 'BOOLEAN', NULL, 'При закрытии дня сохранять остатки материалов')
    MATCHING (VAR_NAME);

end;

COMMIT;
